language: "node_js"
node_js:
  - "8"
install:
  - "npm cache clean --force"
  - "npm install gitbook"
  - "npm install gitbook-cli"
branches:
  only:
    - master
env:
  global:
    - GH_REF: github.com/BellMeng/Blogs.git
script:
  - bash summary_create.sh
  - travis_wait 100 bash deploy.sh
